Getting 4th wellplate from source at 55000
Moving North Track to home position
Priming reservoir 1 line into vial 20: 0.5 mL
Dispensing into vial 20 from reservoir 1: 0.5 mL
Moving vial water to clamp: 0
Grabbing vial
Moving robot to home position
Dispensing 0.5 mL 1 times
Moving vial water to main_8mL_rack: 45
Grabbing vial
CMC estimate: 
0.6559445116842008

Generated concentrations (rough): 
[0.093 0.132 0.189 0.269 0.384 0.549 0.783 1.117 1.595 2.276 3.247 4.634]

 Scaling sub-stock volumes to total 3632.10 킠 (including 500 킠 buffer)
Original total: 6000.00 킠 | Final scaling factor: 0.605
Scaled volumes:
  NaDC: 34.53 킠
  CAPB: 327.99 킠
  water: 3269.58 킠
Traceback (most recent call last):
  File "c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\CMC_rough_refined.py", line 129, in <module>
    sub_stock_vols = change_stock_solution_vial(lash_e, old_name, new_name, volume, sub_stock_vols)
  File "c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\cmc_shared.py", line 23, in change_stock_solution_vial
    volume = lash_e.nr_robot.get_vial_info(surfactant_vial, 'vial_volume')
  File "C:\Users\Imaging Controller\Desktop\utoronto_demo\../utoronto_demo\North_Safe.py", line 1686, in get_vial_info
    vial_index = self.normalize_vial_index(vial_name) #Convert to int if needed
  File "C:\Users\Imaging Controller\Desktop\utoronto_demo\../utoronto_demo\North_Safe.py", line 926, in normalize_vial_index
    raise ValueError(f"Vial name '{vial}' not found in VIAL_DF.")
ValueError: Vial name 'CTAB' not found in VIAL_DF.
