Initializing North Robot...
Physical initialization of North Robot...
Moving robot to home position
   vial_index           vial_name         location  location_index  vial_volume  capped cap_type vial_type    home_location  home_location_index
0           0  measurement_vial_0    main_8mL_rack               0            0    True     open      8_mL    main_8mL_rack                    0
1           1  measurement_vial_1    main_8mL_rack               1            0    True     open      8_mL    main_8mL_rack                    1
2           2  measurement_vial_2    main_8mL_rack               2            0    True     open      8_mL    main_8mL_rack                    2
3           3       liquid_source  large_vial_rack               2           20    True     open     20_mL  large_vial_rack                    2
Visualizing...
Only hit enter if the status of the vials (including open/close) is correct, otherwise hit ctrl-cMoving vial measurement_vial_0 to clamp: 0
Grabbing vial
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Getting pipet number: 0 from rack 1
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.07656387686729432 mL then waiting 0 s
Aspirating 0.01 mL then waiting 22.48070776462555 s
Aspirating 0.03626673817634583 mL then waiting 0 s
C:\Users\Imaging Controller\Desktop\utoronto_demo\../utoronto_demo\North_Safe.py:1014: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '19.99' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  self.VIAL_DF.at[source_vial_num,'vial_volume']=(source_vial_volume-amount_mL)
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.12283061504364014 mL then waiting 5.529413223266602 s
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.07656387686729432 mL then waiting 0 s
Aspirating 0.01 mL then waiting 22.48070776462555 s
Aspirating 0.03626673817634583 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.12283061504364014 mL then waiting 5.529413223266602 s
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.07656387686729432 mL then waiting 0 s
Aspirating 0.01 mL then waiting 22.48070776462555 s
Aspirating 0.03626673817634583 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.12283061504364014 mL then waiting 5.529413223266602 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:85: RuntimeWarning: invalid value encountered in scalar divide
  std_mass = np.std(masses) / avg_mass * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.017835423164069653 mL then waiting 0 s
Aspirating 0.01 mL then waiting 2.4461414013057947 s
Aspirating 0.06696860147640109 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.09480402464047073 mL then waiting 19.878292763605714 s
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.017835423164069653 mL then waiting 0 s
Aspirating 0.01 mL then waiting 2.4461414013057947 s
Aspirating 0.06696860147640109 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.09480402464047073 mL then waiting 19.878292763605714 s
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.017835423164069653 mL then waiting 0 s
Aspirating 0.01 mL then waiting 2.4461414013057947 s
Aspirating 0.06696860147640109 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.09480402464047073 mL then waiting 19.878292763605714 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:85: RuntimeWarning: invalid value encountered in scalar divide
  std_mass = np.std(masses) / avg_mass * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.03968064719811082 mL then waiting 0 s
Aspirating 0.01 mL then waiting 25.44153342023492 s
Aspirating 0.016287294682115316 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.06596794188022613 mL then waiting 12.852779868990183 s
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.03968064719811082 mL then waiting 0 s
Aspirating 0.01 mL then waiting 25.44153342023492 s
Aspirating 0.016287294682115316 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.06596794188022613 mL then waiting 12.852779868990183 s
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.03968064719811082 mL then waiting 0 s
Aspirating 0.01 mL then waiting 25.44153342023492 s
Aspirating 0.016287294682115316 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.06596794188022613 mL then waiting 12.852779868990183 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:85: RuntimeWarning: invalid value encountered in scalar divide
  std_mass = np.std(masses) / avg_mass * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.054781165439635515 mL then waiting 0 s
Aspirating 0.01 mL then waiting 13.368342155590653 s
Aspirating 0.08675120174884797 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.1515323671884835 mL then waiting 27.554954756051302 s
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.054781165439635515 mL then waiting 0 s
Aspirating 0.01 mL then waiting 13.368342155590653 s
Aspirating 0.08675120174884797 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.1515323671884835 mL then waiting 27.554954756051302 s
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.054781165439635515 mL then waiting 0 s
Aspirating 0.01 mL then waiting 13.368342155590653 s
Aspirating 0.08675120174884797 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.1515323671884835 mL then waiting 27.554954756051302 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:85: RuntimeWarning: invalid value encountered in scalar divide
  std_mass = np.std(masses) / avg_mass * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.095604479406029 mL then waiting 0 s
Aspirating 0.01 mL then waiting 6.319280611351132 s
Aspirating 0.0120980653911829 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.11770254479721189 mL then waiting 24.89320646971464 s
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.095604479406029 mL then waiting 0 s
Aspirating 0.01 mL then waiting 6.319280611351132 s
Aspirating 0.0120980653911829 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.11770254479721189 mL then waiting 24.89320646971464 s
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.095604479406029 mL then waiting 0 s
Aspirating 0.01 mL then waiting 6.319280611351132 s
Aspirating 0.0120980653911829 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.11770254479721189 mL then waiting 24.89320646971464 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:85: RuntimeWarning: invalid value encountered in scalar divide
  std_mass = np.std(masses) / avg_mass * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.01136343227699399 mL then waiting 0 s
Aspirating 0.02 mL then waiting 18.62130342051387 s
Aspirating 0.09116187421604992 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.12252530649304391 mL then waiting 9.713714607059956 s
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.01136343227699399 mL then waiting 0 s
Aspirating 0.02 mL then waiting 18.62130342051387 s
Aspirating 0.09116187421604992 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.12252530649304391 mL then waiting 9.713714607059956 s
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.01136343227699399 mL then waiting 0 s
Aspirating 0.02 mL then waiting 18.62130342051387 s
Aspirating 0.09116187421604992 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.12252530649304391 mL then waiting 9.713714607059956 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:85: RuntimeWarning: invalid value encountered in scalar divide
  std_mass = np.std(masses) / avg_mass * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.03326820749789477 mL then waiting 0 s
Aspirating 0.02 mL then waiting 9.741480024531484 s
Aspirating 0.042036968376487495 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.09530517587438227 mL then waiting 17.687284676358104 s
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.03326820749789477 mL then waiting 0 s
Aspirating 0.02 mL then waiting 9.741480024531484 s
Aspirating 0.042036968376487495 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.09530517587438227 mL then waiting 17.687284676358104 s
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.03326820749789477 mL then waiting 0 s
Aspirating 0.02 mL then waiting 9.741480024531484 s
Aspirating 0.042036968376487495 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.09530517587438227 mL then waiting 17.687284676358104 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:85: RuntimeWarning: invalid value encountered in scalar divide
  std_mass = np.std(masses) / avg_mass * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.0736371910199523 mL then waiting 0 s
Aspirating 0.02 mL then waiting 29.082126673310995 s
Aspirating 0.061026137322187424 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.15466332834213972 mL then waiting 1.9196648430079222 s
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.0736371910199523 mL then waiting 0 s
Aspirating 0.02 mL then waiting 29.082126673310995 s
Aspirating 0.061026137322187424 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.15466332834213972 mL then waiting 1.9196648430079222 s
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.0736371910199523 mL then waiting 0 s
Aspirating 0.02 mL then waiting 29.082126673310995 s
Aspirating 0.061026137322187424 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.15466332834213972 mL then waiting 1.9196648430079222 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:85: RuntimeWarning: invalid value encountered in scalar divide
  std_mass = np.std(masses) / avg_mass * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.061055597569793466 mL then waiting 0 s
Aspirating 0.02 mL then waiting 8.133811969310045 s
Aspirating 0.0022374819964170456 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.08329307956621052 mL then waiting 9.17936621233821 s
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.061055597569793466 mL then waiting 0 s
Aspirating 0.02 mL then waiting 8.133811969310045 s
Aspirating 0.0022374819964170456 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.08329307956621052 mL then waiting 9.17936621233821 s
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.061055597569793466 mL then waiting 0 s
Aspirating 0.02 mL then waiting 8.133811969310045 s
Aspirating 0.0022374819964170456 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.08329307956621052 mL then waiting 9.17936621233821 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:85: RuntimeWarning: invalid value encountered in scalar divide
  std_mass = np.std(masses) / avg_mass * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.04605272365733981 mL then waiting 0 s
Aspirating 0.02 mL then waiting 27.93589205481112 s
Aspirating 0.09457562668249012 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.16062835033982992 mL then waiting 23.5378741286695 s
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.04605272365733981 mL then waiting 0 s
Aspirating 0.02 mL then waiting 27.93589205481112 s
Aspirating 0.09457562668249012 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.16062835033982992 mL then waiting 23.5378741286695 s
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.04605272365733981 mL then waiting 0 s
Aspirating 0.02 mL then waiting 27.93589205481112 s
Aspirating 0.09457562668249012 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.16062835033982992 mL then waiting 23.5378741286695 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:85: RuntimeWarning: invalid value encountered in scalar divide
  std_mass = np.std(masses) / avg_mass * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.024158623442053797 mL then waiting 0 s
Aspirating 0.05 mL then waiting 4.176948610693216 s
Aspirating 0.04409116124734283 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.11824978468939663 mL then waiting 1.5046070236712694 s
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.024158623442053797 mL then waiting 0 s
Aspirating 0.05 mL then waiting 4.176948610693216 s
Aspirating 0.04409116124734283 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.11824978468939663 mL then waiting 1.5046070236712694 s
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.024158623442053797 mL then waiting 0 s
Aspirating 0.05 mL then waiting 4.176948610693216 s
Aspirating 0.04409116124734283 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.11824978468939663 mL then waiting 1.5046070236712694 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:85: RuntimeWarning: invalid value encountered in scalar divide
  std_mass = np.std(masses) / avg_mass * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.08298474475741387 mL then waiting 0 s
Aspirating 0.05 mL then waiting 16.017538094893098 s
Aspirating 0.0529187873005867 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.1859035320580006 mL then waiting 16.21271942742169 s
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.08298474475741387 mL then waiting 0 s
Aspirating 0.05 mL then waiting 16.017538094893098 s
Aspirating 0.0529187873005867 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.1859035320580006 mL then waiting 16.21271942742169 s
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.08298474475741387 mL then waiting 0 s
Aspirating 0.05 mL then waiting 16.017538094893098 s
Aspirating 0.0529187873005867 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.1859035320580006 mL then waiting 16.21271942742169 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:85: RuntimeWarning: invalid value encountered in scalar divide
  std_mass = np.std(masses) / avg_mass * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.0675580594688654 mL then waiting 0 s
Aspirating 0.05 mL then waiting 24.295298354700208 s
Aspirating 0.0279617864638567 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.1455198459327221 mL then waiting 21.221702685579658 s
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.0675580594688654 mL then waiting 0 s
Aspirating 0.05 mL then waiting 24.295298354700208 s
Aspirating 0.0279617864638567 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.1455198459327221 mL then waiting 21.221702685579658 s
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.0675580594688654 mL then waiting 0 s
Aspirating 0.05 mL then waiting 24.295298354700208 s
Aspirating 0.0279617864638567 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.1455198459327221 mL then waiting 21.221702685579658 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:85: RuntimeWarning: invalid value encountered in scalar divide
  std_mass = np.std(masses) / avg_mass * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.027091407775878908 mL then waiting 0 s
Aspirating 0.05 mL then waiting 11.76067454740405 s
Aspirating 0.0688267189078033 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.1459181266836822 mL then waiting 6.046315496787429 s
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.027091407775878908 mL then waiting 0 s
Aspirating 0.05 mL then waiting 11.76067454740405 s
Aspirating 0.0688267189078033 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.1459181266836822 mL then waiting 6.046315496787429 s
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.027091407775878908 mL then waiting 0 s
Aspirating 0.05 mL then waiting 11.76067454740405 s
Aspirating 0.0688267189078033 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.1459181266836822 mL then waiting 6.046315496787429 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:85: RuntimeWarning: invalid value encountered in scalar divide
  std_mass = np.std(masses) / avg_mass * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.005235508736222983 mL then waiting 0 s
Aspirating 0.05 mL then waiting 19.876943053677678 s
Aspirating 0.019898648466914894 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.07513415720313787 mL then waiting 29.01396408677101 s
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.005235508736222983 mL then waiting 0 s
Aspirating 0.05 mL then waiting 19.876943053677678 s
Aspirating 0.019898648466914894 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.07513415720313787 mL then waiting 29.01396408677101 s
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.005235508736222983 mL then waiting 0 s
Aspirating 0.05 mL then waiting 19.876943053677678 s
Aspirating 0.019898648466914894 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.07513415720313787 mL then waiting 29.01396408677101 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:85: RuntimeWarning: invalid value encountered in scalar divide
  std_mass = np.std(masses) / avg_mass * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.028958761971443894 mL then waiting 0 s
Aspirating 0.1 mL then waiting 26.706332713365555 s
Aspirating 0.06482507726177573 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.19378383923321962 mL then waiting 17.921504639089108 s
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.028958761971443894 mL then waiting 0 s
Aspirating 0.1 mL then waiting 26.706332713365555 s
Aspirating 0.06482507726177573 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.19378383923321962 mL then waiting 17.921504639089108 s
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.028958761971443894 mL then waiting 0 s
Aspirating 0.1 mL then waiting 26.706332713365555 s
Aspirating 0.06482507726177573 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.19378383923321962 mL then waiting 17.921504639089108 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:85: RuntimeWarning: invalid value encountered in scalar divide
  std_mass = np.std(masses) / avg_mass * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.06388256317004562 mL then waiting 0 s
Aspirating 0.1 mL then waiting 8.546751206740737 s
Aspirating 0.032160264998674394 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.19604282816872 mL then waiting 3.5604772344231606 s
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.06388256317004562 mL then waiting 0 s
Aspirating 0.1 mL then waiting 8.546751206740737 s
Aspirating 0.032160264998674394 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.19604282816872 mL then waiting 3.5604772344231606 s
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.06388256317004562 mL then waiting 0 s
Aspirating 0.1 mL then waiting 8.546751206740737 s
Aspirating 0.032160264998674394 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.19604282816872 mL then waiting 3.5604772344231606 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:85: RuntimeWarning: invalid value encountered in scalar divide
  std_mass = np.std(masses) / avg_mass * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.0008299741894006729 mL then waiting 0 s
Aspirating 0.1 mL then waiting 5.406450172886252 s
Aspirating 0.015309544187039137 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.11613951837643982 mL then waiting 10.885404897853732 s
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.0008299741894006729 mL then waiting 0 s
Aspirating 0.1 mL then waiting 5.406450172886252 s
Aspirating 0.015309544187039137 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.11613951837643982 mL then waiting 10.885404897853732 s
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.0008299741894006729 mL then waiting 0 s
Aspirating 0.1 mL then waiting 5.406450172886252 s
Aspirating 0.015309544187039137 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.11613951837643982 mL then waiting 10.885404897853732 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:85: RuntimeWarning: invalid value encountered in scalar divide
  std_mass = np.std(masses) / avg_mass * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.047897093743085865 mL then waiting 0 s
Aspirating 0.1 mL then waiting 12.406155494973063 s
Aspirating 0.09057093476876617 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.23846802851185203 mL then waiting 11.680859634652734 s
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.047897093743085865 mL then waiting 0 s
Aspirating 0.1 mL then waiting 12.406155494973063 s
Aspirating 0.09057093476876617 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.23846802851185203 mL then waiting 11.680859634652734 s
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.047897093743085865 mL then waiting 0 s
Aspirating 0.1 mL then waiting 12.406155494973063 s
Aspirating 0.09057093476876617 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.23846802851185203 mL then waiting 11.680859634652734 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:85: RuntimeWarning: invalid value encountered in scalar divide
  std_mass = np.std(masses) / avg_mass * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.05750379227101803 mL then waiting 0 s
Aspirating 0.1 mL then waiting 22.833193726837635 s
Aspirating 0.006439013779163361 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.1639428060501814 mL then waiting 26.851899856701493 s
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.05750379227101803 mL then waiting 0 s
Aspirating 0.1 mL then waiting 22.833193726837635 s
Aspirating 0.006439013779163361 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.1639428060501814 mL then waiting 26.851899856701493 s
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.05750379227101803 mL then waiting 0 s
Aspirating 0.1 mL then waiting 22.833193726837635 s
Aspirating 0.006439013779163361 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.1639428060501814 mL then waiting 26.851899856701493 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:85: RuntimeWarning: invalid value encountered in scalar divide
  std_mass = np.std(masses) / avg_mass * 100  # % relative std
Removing pipet
Moving vial measurement_vial_0 to main_8mL_rack: 0
Grabbing vial
Moving robot to home position
    deviation  variability        time  aspirate_speed  dispense_speed  aspirate_wait_time  dispense_wait_time  retract_speed  pre_asp_air_vol  post_asp_air_vol  volume  trial_index strategy liquid               time_reported
0    5.305298     1.018594  137.403975              10               9           22.480708            5.529413       8.707314         0.076564          0.036267    0.01            0    SOBOL  water  2025-07-17T19:42:15.425929
1    4.698839     2.781023  -83.581845              19              29            2.446141           19.878293       3.065669         0.017835          0.066969    0.01            1    SOBOL  water  2025-07-17T19:42:15.682275
2   12.164017     0.131991  167.855999              27              15           25.441533           12.852780       7.693378         0.039681          0.016287    0.01            2    SOBOL  water  2025-07-17T19:42:15.920563
3    2.064727     1.050849   26.887242              17              23           13.368342           27.554955      12.555739         0.054781          0.086751    0.01            3    SOBOL  water  2025-07-17T19:42:16.162893
4    2.858654     2.988069  -25.692096              12              14            6.319281           24.893206      13.678921         0.095604          0.012098    0.01            4    SOBOL  water  2025-07-17T19:42:16.415625
5   13.084959     1.057501   96.533084              29              18           18.621303            9.713715       5.319763         0.011363          0.091162    0.02            5    SOBOL  water  2025-07-17T19:42:16.674177
6    5.929190     2.286939   -0.267393              21               7            9.741480           17.687285       1.949440         0.033268          0.042037    0.02            6    SOBOL  water  2025-07-17T19:42:16.910087
7   10.650817     0.034163  193.658746               5              25           29.082127            1.919665      11.087881         0.073637          0.061026    0.02            7    SOBOL  water  2025-07-17T19:42:17.174170
8    8.194306     2.283987  -10.876771               7              17            8.133812            9.179366       3.820102         0.061056          0.002237    0.02            8    SOBOL  water  2025-07-17T19:42:17.441083
9    8.032903     0.220023  180.854006              23              21           27.935892           23.537874       9.462026         0.046053          0.094576    0.02            9    SOBOL  water  2025-07-17T19:42:17.691428
10  15.165884     3.116802  -54.476167              30              10            4.176949            1.504607      11.779190         0.024159          0.044091    0.05           10    SOBOL  water  2025-07-17T19:42:17.936264
11   1.415625     1.689683   60.046695              14              28           16.017538           16.212719       6.916576         0.082985          0.052919    0.05           11    SOBOL  water  2025-07-17T19:42:18.188725
12   0.336869     0.599889  140.516053              15               5           24.295298           21.221703       5.848725         0.067558          0.027962    0.05           12    SOBOL  water  2025-07-17T19:42:18.450512
13   9.399229     1.476762   18.644708              25              26           11.760675            6.046315      14.207708         0.027091          0.068827    0.05           13    SOBOL  water  2025-07-17T19:42:18.706458
14   3.437609     0.757331   90.672648              18              12           19.876943           29.013964      10.522930         0.005236          0.019899    0.05           14    SOBOL  water  2025-07-17T19:42:18.958549
15   6.011985     0.238607  160.486945               9              11           26.706333           17.921505      13.093019         0.028959          0.064825    0.10           15    SOBOL  water  2025-07-17T19:42:19.246201
16   3.010041     2.635902  -15.580475              18              20            8.546751            3.560477       7.346232         0.063883          0.032160    0.10           16    SOBOL  water  2025-07-17T19:42:19.529228
17   1.229390     2.588716  -48.588524              14              27            5.406450           10.885405       8.136772         0.000830          0.015310    0.10           17    SOBOL  water  2025-07-17T19:42:19.788237
18   1.650112     1.600082   14.431713              13              10           12.406155           11.680860      10.958674         0.047897          0.090571    0.10           18    SOBOL  water  2025-07-17T19:42:20.058794
19  15.286822     0.448533  128.344659              30              28           22.833194           26.851900       2.706262         0.057504          0.006439    0.10           19    SOBOL  water  2025-07-17T19:42:20.328495
