Initializing North Robot...
Physical initialization of North Robot...
Moving robot to home position
   vial_index           vial_name         location  location_index  vial_volume  capped cap_type vial_type    home_location  home_location_index
0           0  measurement_vial_0    main_8mL_rack               0         7.08    True     open      8_mL    main_8mL_rack                    0
1           1  measurement_vial_1            clamp               0         6.80    True     open      8_mL    main_8mL_rack                    1
2           2  measurement_vial_2    main_8mL_rack               2         0.00    True     open      8_mL    main_8mL_rack                    2
3           3       liquid_source  large_vial_rack               2       500.00    True     open     20_mL  large_vial_rack                    2
Visualizing...
Only hit enter if the status of the vials (including open/close) is correct, otherwise hit ctrl-c--Wellplate status-- 
 Wellplate type: 48 WELL PLATE 
 Number in source: 4 
 Number in waste: 0 
 NR Pipetting area occupied: False
Only hit enter if the status of the well plates is correct, otherwise hit ctrl-cGetting 4th wellplate from source at 55000
Moving North Track to home position
Traceback (most recent call last):
  File "c:\Users\owenm\OneDrive\Desktop\North Robotics\utoronto_demo\utoronto_demo\workflows\calibration_sdl_short_abs.py", line 119, in <module>
    suggestions = recommender.get_suggestions(ax_client, volume, n=SOBOL_CYCLES_PER_VOLUME)
  File "C:\Users\owenm\OneDrive\Desktop\North Robotics\utoronto_demo\utoronto_demo\../utoronto_demo\recommenders\pipeting_optimizer_honegumi.py", line 102, in get_suggestions
    params, trial_index = ax_client.get_next_trial(
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\utils\common\executils.py", line 167, in actual_wrapper
    return func(*args, **kwargs)
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\service\ax_client.py", line 543, in get_next_trial
    generator_run=self._gen_new_generator_run(
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\service\ax_client.py", line 1781, in _gen_new_generator_run
    return not_none(self.generation_strategy).gen(
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\modelbridge\generation_strategy.py", line 372, in gen
    return self._gen_multiple(
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\modelbridge\generation_strategy.py", line 786, in _gen_multiple
    generator_run = self._curr.gen(
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\modelbridge\generation_node.py", line 807, in gen
    gr = super().gen(
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\modelbridge\generation_node.py", line 334, in gen
    generator_run = self._gen(
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\modelbridge\generation_node.py", line 396, in _gen
    return model_spec.gen(
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\modelbridge\model_spec.py", line 235, in gen
    generator_run = fitted_model.gen(**model_gen_kwargs)
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\modelbridge\base.py", line 777, in gen
    gen_results = self._gen(
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\modelbridge\random.py", line 76, in _gen
    X, w = self.model.gen(
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\models\random\sobol.py", line 108, in gen
    points, weights = super().gen(
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\models\random\base.py", line 176, in gen
    raise e
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\models\random\base.py", line 134, in gen
    points, attempted_draws = rejection_sample(
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\models\model_utils.py", line 150, in rejection_sample
    raise SearchSpaceExhausted(
ax.exceptions.core.SearchSpaceExhausted: Rejection sampling error (specified maximum draws (10000) exhausted, without finding sufficiently many (1) candidates). This likely means that there are no new points left in the search space.
